---
# Image name for provisioning tools or records
ansible_host_image: windows-10-x86_64

# Default connection details (override sensitive values in Vault or inventory)
ansible_user: Administrator
ansible_password: Password123
ansible_connection: winrm
ansible_winrm_transport: ntlm
ansible_port: 5985
ansible_winrm_server_cert_validation: ignore
