---
- name: Test Windows host
  hosts: windows
  gather_facts: no
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_port: 5985
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Test connectivity with win_ping
      win_ping:
